In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/Users/ichang-ug/Documents/GitHub/esports_YSAL/LOL/Data/BR10_fix.csv")
data

,blueWins,blueTotalGolds,blueTotalLevel,blueTotalMinionKills,blueTotalJungleMinionKills,blueTotalDamageToChampion,blueFirstBlood,blueKill,blueDeath,blueAssist,...,blueAIR_DRAGON,blueEARTH_DRAGON,blueCHEMTECH_DRAGON,blueHEXTECH_DRAGON,redWATER_DRAGON,redFIRE_DRAGON,redAIR_DRAGON,redEARTH_DRAGON,redCHEMTECH_DRAGON,redHEXTECH_DRAGON
0,1,13923,28,189,48,13052,1,10,2,4,...,0,0,0,0,0,0,0,0,0,0
1,1,12441,26,167,0,11163,1,8,4,4,...,0,0,0,0,0,0,0,0,0,0
2,0,13680,27,159,48,13722,0,10,6,8,...,0,0,0,0,0,0,0,1,0,0
3,1,11416,27,168,40,8524,1,3,3,2,...,0,0,0,0,0,1,0,0,0,0
4,1,12225,29,156,50,12787,1,7,2,3,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,0,11892,26,170,44,14062,0,4,8,2,...,0,0,0,0,0,0,0,0,0,0
192,1,12042,26,145,42,10991,0,6,9,5,...,0,0,0,0,0,0,0,0,0,0
193,1,12253,27,192,56,8597,1,3,2,5,...,0,0,0,0,0,0,0,0,0,0
194,0,10847,24,138,44,6092,1,5,5,3,...,0,0,0,0,0,0,0,0,0,0
195,1,11313,25,150,38,10455,0,5,4,9,...,0,0,0,0,0,0,0,0,0,0

In [9]:
cl10 = pd.read_csv("/Users/ichang-ug/Documents/GitHub/esports_YSAL/LOL/Data/CL10.csv")
cl15 = pd.read_csv("/Users/ichang-ug/Documents/GitHub/esports_YSAL/LOL/Data/CL15.csv")
gm10 = pd.read_csv("/Users/ichang-ug/Documents/GitHub/esports_YSAL/LOL/Data/GM10.csv")
gm15 = pd.read_csv("/Users/ichang-ug/Documents/GitHub/esports_YSAL/LOL/Data/GM15.csv")


dfs = [cl10, cl15, gm10, gm15]

In [5]:
cl10["blueTotalGolds"]

0       16971
1       15858
2       14794
3       13863
4       18289
        ...
1516    17041
1517    16170
1518    19031
1519    17613
1520    13788
Name: blueTotalGolds, Length: 1521, dtype: int64

In [10]:
for df in dfs:
# Gap ë³€ìˆ˜ë¡œ ë³€í™˜
  df['TotalGold_Gap'] = df['blueTotalGolds'] - df['redTotalGolds']
  df['AvgLever_Gap'] = df['blueAvgLevel'] - df['redAvgLevel']
  df['TotalMinionKills_Gap'] = df['blueTotalMinionKills'] - df['redTotalMinionKills']
  df['TotalJungleMinionKills_Gap'] = df['blueTotalJungleMinionKills'] - df['redTotalJungleMinionKills']
  df['TotalDamageToChampion_Gap'] = df['blueTotalDamageToChampion'] - df['redTotalDamageToChampion']
  df['Kill_Gap'] = df['blueKill'] - df['redKill']
  df['Assist_Gap'] = df['blueAssist'] - df['redAssist']
  df['WardPlaced_Gap'] = df['blueWardPlaced'] - df['redWardPlaced']
  df['WardKills_Gap'] = df['blueWardKills'] - df['redWardKills']
  df['TowerKills_Gap'] = df['blueTowerKills'] - df['redTopTowerKills']
  df['MidTowerKills_Gap'] = df['blueMidTowerKills'] - df['redMidTowerKills']
  df['TopTowerKills_Gap'] = df['blueTopTowerKills'] - df['redTopTowerKills']
  df['BotTowerKills_Gap'] = df['blueBotTowerKills'] - df['redBotTowerKills']
  df['Inhibitor_Gap'] = df['blueInhibitor'] - df['redInhibitor']
  df['Dragon_Gap'] = df['blueDragon'] - df['redDragon']
  df['RiftHeralds_Gap'] = df['blueRiftHeralds'] - df['redRiftHeralds']
  df["humanPrediction"] = 0
  df["1"] = 1
  df["humanPrediction"][df["Kill_Gap"]>0] =df["1"][df["Kill_Gap"]>0]
  df.drop("1", axis=1, inplace=True)

  df.drop(columns=['Unnamed: 0', 'gameId', 'blueTotalGolds',
        'blueCurrentGolds', 'blueTotalLevel', 'blueAvgLevel',
        'blueTotalMinionKills', 'blueTotalJungleMinionKills',
        'blueTotalDamageToChampion', 'blueKill', 'blueDeath',
        'blueAssist', 'blueWardPlaced', 'blueWardKills',
        'blueFirstTowerLane', 'blueTowerKills',
        'blueMidTowerKills', 'blueTopTowerKills', 'blueBotTowerKills',
        'blueInhibitor', 'blueDragonType', 'blueDragon',
        'blueRiftHeralds', 'redWins', 'redTotalGolds', 'redCurrentGolds',
        'redTotalLevel', 'redAvgLevel', 'redTotalMinionKills',
        'redTotalJungleMinionKills', 'redTotalDamageToChampion',
        'redFirstBlood', 'redKill', 'redDeath', 'redAssist', 'redWardPlaced',
        'redWardKills', 'redFirstTower', 'redFirstInhibitor',
        'redFirstTowerLane', 'redTowerKills', 'redMidTowerKills',
        'redTopTowerKills', 'redBotTowerKills', 'redInhibitor',
        'redFirstDragon', 'redDragonType', 'redDragon', 'redRiftHeralds'], axis=1, inplace = True)

/var/folders/qy/nr8yjnh91mb1wc8h2lycqghc0000gn/T/ipykernel_62033/1325378034.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["humanPrediction"][df["Kill_Gap"]>0] =df["1"][df["Kill_Gap"]>0]
/var/folders/qy/nr8yjnh91mb1wc8h2lycqghc0000gn/T/ipykernel_62033/1325378034.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["humanPrediction"][df["Kill_Gap"]>0] =df["1"][df["Kill_Gap"]>0]
/var/folders/qy/nr8yjnh91mb1wc8h2lycqghc0000gn/T/ipykernel_62033/1325378034.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["humanPrediction"][df["Kill_Gap"]>0] =df["1"][df["Kill_Gap"]>0]
/var/folders/qy/nr8yjnh91mb1wc8h2lycqghc0000gn/T/ipykernel_62033/1325378034.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["humanPrediction"][df["Kill_Gap"]>0] =df["1"][df["Kill_Gap"]>0]

In [11]:
cl10.to_csv("/Users/ichang-ug/Documents/GitHub/esports_YSAL/LOL/Data/CL10_gap.csv")
cl15.to_csv("/Users/ichang-ug/Documents/GitHub/esports_YSAL/LOL/Data/CL15_gap.csv")
gm10.to_csv("/Users/ichang-ug/Documents/GitHub/esports_YSAL/LOL/Data/GM10_gap.csv")
gm15.to_csv("/Users/ichang-ug/Documents/GitHub/esports_YSAL/LOL/Data/GM15_gap.csv")

,blueWins,blueFirstBlood,blueFirstTower,blueFirstInhibitor,blueFirstDragon,matchMin,TotalGold_Gap,AvgLever_Gap,TotalMinionKills_Gap,TotalJungleMinionKills_Gap,...,WardPlaced_Gap,WardKills_Gap,TowerKills_Gap,MidTowerKills_Gap,TopTowerKills_Gap,BotTowerKills_Gap,Inhibitor_Gap,Dragon_Gap,RiftHeralds_Gap,humanPrediction
0,True,1,0,0,1,41,558,0.4,1,12,...,-7,1,0,0,0,0,0,1,0,1
1,True,0,0,0,1,26,124,0.0,-7,6,...,-1,2,0,0,0,0,0,1,-1,1
2,True,1,0,0,0,33,-879,-0.2,-18,11,...,3,-3,0,0,0,0,0,0,1,0
3,False,1,0,0,1,21,-666,-0.2,-13,-7,...,-4,0,0,0,0,0,0,1,0,0
4,False,1,0,0,0,34,2728,0.2,11,-16,...,1,3,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1516,True,1,0,0,0,22,2227,0.4,23,15,...,-1,0,0,0,0,0,0,-1,1,1
1517,False,1,0,0,0,22,-258,0.2,-1,0,...,19,-3,0,0,0,0,0,-1,0,0
1518,True,1,0,0,0,23,3316,0.6,25,-1,...,-1,0,0,0,0,0,0,-1,0,1
1519,True,1,0,0,0,18,3439,0.0,17,15,...,16,6,0,0,0,0,0,0,0,1
1520,False,0,0,0,0,22,-1524,-0.4,-9,8,...,2,-1,0,0,0,0,0,0,1,0

In [48]:
np.mean(gm15["blueTotalGolds"]-gm15["redTotalGolds"])

-9.214509394572024

In [80]:
cl10["blueTotalGolds"]

KeyError: 'blueTotalGolds'

In [20]:
df["Reversal"]=0

In [23]:
df["Reversal"][df["blueWins"]==0]

0      0
1      0
2      0
6      0
7      0
      ..
190    0
192    0
194    0
198    0
199    0
Name: Reversal, Length: 103, dtype: int64